# action codes: KEEP, REBUILD, UPDATE, MERGE, MOVE, CUT   |  dest = new location
D = {
# ---- Deck 1: Επισκόπηση ----
'1.1':('MERGE','W1·P1','Becomes the new title slide. The sketch-note image is third-party with no credit on the slide: I need its source, or I replace it.'),
'1.2':('CUT','','A round of five introductions per student costs 10+ minutes of Part 1 on Zoom. Optional replacement: one 45-second Zoom poll on background (statistics / data mining / LA / educational research) that gives you the same calibration.'),
'1.3':('REBUILD','W1·P1','Topic timeline replaced by the new three-week roadmap.'),
'1.4':('UPDATE','W1·P1','Learning objectives kept, rewritten to match the new backbone, max 4 short lines (now 65 words, justified text).'),
'1.5':('MOVE','W1·P3','83 words. Grading (75/25) and "individual or pairs" contradict the brief. Split over 5-6 slides in the assignment launch; the brief becomes the single source of truth.'),
# ---- Deck 2: Εισαγωγή ----
'2.1':('CUT','','Second title slide; stock "5W signs" image.'),
'2.2':('REBUILD','W1·P1','Your definition (kept in your translation) + the five facets (Πλαίσιο, Επίπεδα, Αντικείμενα, Σκοπός, Ενδιαφερόμενα Μέρη). 80 words on an atom graphic that overflows. Rebuilt as a definition slide + four build-up slides.'),
'2.3':('MERGE','W1·P1','"Εν συντομία" road graphic folds into the step-by-step LA cycle.'),
'2.4':('UPDATE','W1·P2','Loco-Analyst dates from 2007; Blackboard Analytics has been rebranded. Replaced by a current landscape slide (Moodle Analytics, OU Analyse, ViLLE, GenAI-based tools).'),
'2.5':('REBUILD','W1·P2','Good content (Ιστορικό, Αξιολόγηση, Δημογραφικά, Ψηφιακά, Ψυχομετρικά). Native table, revealed column by column.'),
'2.6':('CUT','W2·P1 (1 slide)','62 words of algorithm names (ID3/C4.5/CART/SPRINT, SVM, Bayesian nets). The programme has dedicated ML courses. One "question -> method family" slide survives in Week 2.'),
'2.7':('MOVE','W2·P3','Visualisation taxonomy, condensed to one slide in the dashboards part.'),
'2.8':('UPDATE','W1·P1','Your five challenges kept as the frame, refreshed with 2022-2025 sources (bias, transferability, GenAI, regulation).'),
'2.9':('REBUILD','W1·P1','Becomes the "Να θυμάστε" closing slide; "The End" stock graphic dropped.'),
# ---- Deck 3: Δεδομένα ----
'3.1':('CUT','','Third title slide. The data-drill cartoon (timoelliott.com, credited) can open Part 2 if you want it.'),
'3.2':('KEEP','W1·P2','Opens Part 2: four reasons in four verbs. Cartoon optional.'),
'3.3':('MERGE','W1·P2','"Why is effectiveness hard to prove" merges with 3.2-3.4 into one slide. Portrait photo dropped.'),
'3.4':('MERGE','W1·P2','59 words -> three principles on one slide. The confidentiality point moves to ethics.'),
'3.5':('CUT','','Section slide with stock illustration, 3 words.'),
'3.6':('REBUILD','W1·P1','Six goals of LA. Currently a low-resolution screenshot of text; rebuilt as native text under "Γιατί;".'),
'3.7':('UPDATE','W1·P1','Pros and cons, also a screenshot of text. Rebuilt as "υπόσχεση και πραγματικότητα" with recent evidence.'),
'3.8':('REBUILD','W1·P1','Your simple cycle (Εκπαιδευτικός - Μαθητές - Δεδομένα χρήστη - ΜΑ). Rebuilt natively and revealed step by step. Clip-art dropped.'),
'3.9':('REBUILD','W1·P2','Your "Reality" data cycle, a screenshot of a dense Greek diagram. Rebuilt as a 5-6 step build. Your "simple vs reality" device is kept.'),
'3.10':('REBUILD','W1·P2','Indicators by level (Μαθητής, Ομάδα, Κοινότητα, Υπηρεσίες). 72 words -> four build slides.'),
'3.11':('UPDATE','W1·P2','109 words. Source/frequency/duration/interval comes from behavioural observation. Replaced by trace-data indicator families (frequency, time-on-task, regularity, sequence) with recent sources.'),
'3.12':('REBUILD','W1·P2','Physical, bio-physiological, digital traces. 1-2 slides; links forward to your immersive-technology part.'),
'3.13':('CUT','','Four stock classroom photos, no message.'),
'3.14':('CUT','','Five small, low-resolution software screenshots.'),
'3.15':('CUT','','Five more. If you want one collage slide from 3.14-3.15, tell me which tools matter.'),
'3.16':('REBUILD','W1·P2','LMS/MOOC logo collage -> one clean slide "πού παράγονται τα ίχνη".'),
'3.17':('CUT','','Section slide. Dilbert strip is third-party and low-resolution (51 px/in).'),
'3.18':('CUT','','The 5 Vs: generic big-data content for a CS cohort.'),
'3.19':('CUT','','Structured / unstructured / semi-structured, 77 words: belongs to the database half of the course.'),
'3.20':('REBUILD','W1·P1','Value-vs-complexity figure (58 px/in, blurry when large). Rebuilt natively in four steps.'),
'3.21':('MERGE','W1·P1','Your guiding questions per analytics type are kept verbatim and merged into the 3.20 build.'),
'3.22':('CUT','','Section slide with cartoons.'),
'3.23':('MOVE','W2·P1','Εύρεση Δομών και Προτύπων, with your examples. Goes to "methods by question".'),
'3.24':('MOVE','W2·P1','Πρόβλεψη, with your examples.'),
'3.25':('MOVE','W2·P1','Εξόρυξη σχέσεων, with your examples.'),
'3.26':('MOVE','W2·P3','Chart-types poster (66 px/in). Goes to dashboards, probably rebuilt.'),
'3.27':('MOVE','W2·P3','Dashboard screenshot collage. I will pick the best one or two with you.'),
'3.28':('MOVE','W2·P3','Predictive-tool screenshots.'),
'3.29':('CUT','','Four research figures with no text. No message without narration.'),
'3.30':('CUT','','Tools wheel. Start of the nine-slide tools tour.'),
'3.31':('CUT','','SQL / NoSQL, 78 words.'),
'3.32':('CUT','','Excel.'),
'3.33':('CUT','','R vs Python table, 110 words.'),
'3.34':('CUT','','TensorFlow.'),
'3.35':('CUT','','NLTK.'),
'3.36':('CUT','','Spark, 102 words.'),
'3.37':('CUT','','Jupyter.'),
'3.38':('CUT','','D3 / React, 77 words. The whole tour (3.30-3.38) is replaced by ONE slide: the LA technology stack (LMS -> xAPI/Caliper -> LRS -> αποθήκη -> dashboard), which links to the database half.'),
'3.39':('REBUILD','W1·P2','Moodle analytics pipeline (raw data -> indicators -> target -> model -> predictions -> insights -> actions). Strong content; rebuilt as a step-by-step build.'),
'3.40':('KEEP','W1·P2','ViLLE opener. Please confirm the current figure for "65% των σχολείων".'),
'3.41':('KEEP','W1·P2','Your screenshots, reused as they are.'),
'3.42':('KEEP','W1·P2','Can share a slide with 3.41.'),
'3.43':('KEEP','W1·P2','Dashboard screenshots, shown large.'),
'3.44':('KEEP','W1·P2','Dashboard screenshots, shown large.'),
'3.45':('KEEP','W1·P2','Misconception heatmap: the best single example of diagnostic analytics in the deck.'),
'3.46':('KEEP','W1·P2','Automatic grading.'),
'3.47':('KEEP','W1·P2','Study-habit heatmaps.'),
'3.48':('KEEP','W1·P2','This is a 402-frame animation. It plays natively in the HTML deck (it dies in any PDF export).'),
'3.49':('KEEP','W1·P2','Longitudinal boxplots 2018-2021: your evidence slide. It needs its citation on the slide.'),
'3.50':('REBUILD','W1·P1 / P2','86 words. Split between "Να θυμάστε" (Part 1) and the close of Part 2.'),
'3.51':('KEEP','W1·P2','Your three "Προβληματισμοί" close Part 2.'),
# ---- Deck 4: Θέματα Ηθικής ----
'4.1':('CUT','','Title slide. Glasbergen cartoon is third-party.'),
'4.2':('UPDATE','W3·P2','92 words. Recommendations 14-15 come from a 2014 EU report that predates GDPR. Replaced by GDPR + the EU AI Act (2024) + Kaliisa, Baker, Wasson & Prinsloo (2025).'),
'4.3':('REBUILD','W3·P2','Consent question. All seven of your questions are kept, but attached to decisions the students have just made in lab 2.'),
'4.4':('CUT','','Madame Zaza cartoon, 55 px/in.'),
'4.5':('REBUILD','W3·P2','Data ownership and access.'),
'4.6':('KEEP','W3·P2','Marketoonist cartoon: keep at most two cartoons in the ethics part, with credit.'),
'4.7':('REBUILD','W3·P2','Reliability of results.'),
'4.8':('CUT','','Cartoon, 61 px/in.'),
'4.9':('REBUILD','W3·P2','Misinterpretation.'),
'4.10':('CUT','','Cartoon only.'),
'4.11':('REBUILD','W3·P2','Duty to act on a dropout prediction: becomes the central dilemma of lab 2.'),
'4.12':('CUT','','Cartoon only.'),
'4.13':('REBUILD','W3·P2','Student autonomy.'),
'4.14':('CUT','','Cartoon only.'),
'4.15':('REBUILD','W3·P2','Human in the loop: ties directly to the AI Act.'),
'4.16':('KEEP','W3·P2','Teacher quote. It needs a source on the slide.'),
'4.17':('MERGE','W3·P2','Merges with 4.16.'),
'4.18':('CUT','','Cartoon only.'),
'4.19':('KEEP','W1·P1 + W3·P2','"Μαθησιακή Αναλυτική ή Παρακολούθηση Μαθητών;" also closes Week 1 Part 1 as a teaser.'),
'4.20':('UPDATE','W3·P2','NYT Illuminate breach (2022). One 9.2 MB animation is 80% of this deck\'s file size. Kept as a still, plus a 2024-25 case.'),
'4.21':('KEEP','W3·P2','Closing question.'),
# ---- Deck 5: Συστηματική Ανασκόπηση ----
'5.1':('CUT','','Title slide; PhD Comics strip is third-party.'),
'5.2':('REBUILD','W1·P3','Eight question-answer lines that overflow the slide. Two slides.'),
'5.3':('REBUILD','W1·P3','126 words. PICO plus question development -> 4-5 slides with a worked LA example. PCC/PICo added for questions with no intervention.'),
'5.4':('UPDATE','W1·P3 + W3·P3','The flow diagram is PRISMA 2009. Replaced by PRISMA 2020 (Page et al., 2021), rebuilt natively, revealed step by step.'),
'5.5':('REBUILD','W1·P3 + W2·P3','119 words. Overview in Week 1; the working session (databases, Boolean string, search log) in Week 2.'),
'5.6':('REBUILD','W3·P3','Two unreadable table screenshots. Becomes the extraction workshop + a template sheet.'),
'5.7':('UPDATE','W1·P3','Structure slide kept. "Mendeley" here vs Zotero in your guidelines file: aligned.'),
}
