# Week 2 source decks (6-9): action codes KEEP, REBUILD, UPDATE, MERGE, MOVE, CUT | dest = new location | reason
# Already routed here from Week 1 (see decisions.py): 3.23-3.25 and 2.6 -> W2·P1 ; 2.7 and 3.26-3.28 -> W2·P3
D2 = {
# ---- Deck 6: Τεχνολογίες Εμβύθισης (your immersive-technology LA framework) -> Week 3, Part 3 ----
'6.1':('CUT','','Title slide. The cartoon is third-party (your own note on 6.3 points to a poster shop) and carries no credit on the slide.'),
'6.2':('MERGE','W3·P3','Six-topic "atom" overview. Same graphic as 6.6 with less text: merges into the 6.6 build as its first step.'),
'6.3':('CUT','','A recap of what Learning Analytics is (interdisciplinary, big data, machine learning, visualisation) on stock "Big Data" clip-art. By Week 3 the students have had two evenings of this.'),
'6.4':('UPDATE','W3·P3','VR (three immersion levels) and AR (three augmentation types) plus benefits: 56 words in seven overlapping text boxes. One slide survives, turned towards the point of the part: which NEW traces these devices produce. Links back to the bio-physiological traces slide of Week 1, Part 2.'),
'6.5':('REBUILD','W3·P3','Your argument for the framework: LA is tied to LMS data that are easy to reach, so few frameworks exist for immersive settings. 64 words plus a SmartArt. Two slides: the gap, then the proposal.'),
'6.6':('REBUILD','W3·P3','The framework overview. Text runs off the slide at the bottom right. Rebuilt natively and revealed dimension by dimension (Τεχνολογία, Παιδαγωγική, Ψυχολογία, then Μαθησιακή Αναλυτική).'),
'6.7':('REBUILD','W3·P3','Framework cycle (Ενδιαφερόμενα Μέλη, Ταξινόμηση Δεδομένων, Μετρήσεις, Μαθησιακή Αναλυτική). It is a picture of a diagram with Greek text inside it, so it is rebuilt natively. Your four guiding questions tie it to "Τύποι αναλυτικής" from Week 1.'),
'6.8':('KEEP','W3·P3','Data-collection table (Τεχνολογικά / Παιδαγωγικά / Ψυχολογικά x πηγή x τύπος x παραδείγματα). Your strongest slide in this deck. Native table, revealed one row group at a time because 71 words at once is too many.'),
'6.9':('UPDATE','W3·P3','Analysis table (επίπεδο x στόχος x μοντέλο x οπτικοποίηση). Levels, goals and visualisations stay. The model column assigns decision trees, random forests or Naive Bayes to each level; a CS cohort will challenge that, so it is presented as "ενδεικτικά", exactly as published.'),
'6.10':('KEEP','W3·P3','System architecture figure: 2937 px wide, the sharpest image in the four decks, and your own composition. Reused as it is, shown large. The "To be or not to be" closing graphic is dropped. The framework paper goes on the slide as the source.'),
# ---- Deck 7: Ενδεικτικά Παραδείγματα ----
'7.1':('CUT','','Title slide; Andertoons cartoon is third-party.'),
'7.2':('REBUILD','W2·P1','Section opener for the novice-programmer study. The "Barriers to Learning to Program" figure is from a paper that is not credited anywhere in the deck and I could not identify it, so the opener is rebuilt without it.'),
'7.3':('KEEP','W2·P1','Your best teaching device in the four decks: same students, same grades, then the attempts column appears (1500, 348, 200, 410, 100, 1100). The three table screenshots become one native table in two steps, with your numbers and your sentence «Το περιεχόμενο των υποβολών (code submissions) έχει σημασία».'),
'7.4':('REBUILD','W2·P1','From submission to sequence: E / S, Μαθητής Α: EEEEEE, Μαθητής Β: ESSSSS, pairs of consecutive submissions. Rebuilt natively as one step of the build.'),
'7.5':('REBUILD','W2·P1 (skippable)','Markov chain in one picture (rain / sun, 25-75-0-100%). Both images are third-party and uncredited. Rebuilt natively as a two-state chain with your numbers. Marked skippable: a CS cohort has met Markov chains.'),
'7.6':('REBUILD','W2·P1','The four transitions (E,S), (E,E), (S,E), (S,S) with "?" on the arrows. Rebuilt natively; the question marks become the numbers of the worked example.'),
'7.7':('UPDATE','W2·P1','State machine. The slide mixes working names (Same error, Continued success, Same success) with «Confused», which only the JISE paper uses; the Informatics in Education paper calls that state «Repeated error». Rebuilt natively with the eight states of Lokkila, Christopoulos & Laakso (2023, Informatics in Education, Fig. 1), because the data slide comes from that paper; the JISE label goes in the notes.'),
'7.8':('UPDATE','W2·P1','Transition matrix with x marks. Same naming issue: «Recovered» appears in neither of the two papers I opened. Rebuilt natively from the published adjacency table (Informatics in Education, Table 1), followed by the four-step algorithm (Collate, Aggregate, Normalize, Finalize).'),
'7.9':('KEEP','W2·P1 (skippable)','Your t-SNE figure, Java against Python. Reused as it is with your caption. The claim on the slide is sourced to the JISE paper; the t-SNE plot itself does not appear in the two papers I opened, so it is labelled as your own visualisation.'),
'7.10':('MERGE','W2·P1','k-means. The boxplot is 392 px wide (96 px per inch) and cannot be shown large; its message (clusters differ in perceived difficulty) is stated natively from the ITiCSE 2022 paper. The scatter plot merges with 7.11.'),
'7.11':('KEEP','W2·P1','k-means scatter with your two dividing lines and your two questions («Προβλήματα να γράψουν κώδικα;», «Προβλήματα στην επίλυση προβλημάτων;»). Reused as it is; the two questions move to the «Προβληματισμοί» slide because they are interpretation, not result.'),
'7.12':('MOVE','W3·P3','VR robotics study, opener with your simulator screenshot (1920 px, sharp). It is the applied example of the deck 6 framework, so it goes next to it.'),
'7.13':('MOVE','W3·P3','129 words, in English: data-collection stages plus the analysis list. Becomes two slides (what was collected and where; how it was analysed), Greek headings with the English terms kept.'),
'7.14':('MOVE','W3·P3','87 words, in English, plus the engagement chart. Condensed to three findings. It needs its publication on the slide; I will identify and verify it when we reach Week 3.'),
'7.15':('MOVE','W2·P3','Collage of ViLLE charts from that course. Candidate specimen for the dashboards part ("which decision does each chart support?"). Final call at the Part 3 outline.'),
'7.16':('CUT','','Third-party cartoon, 600 px stretched over the full slide (49 px per inch).'),
# ---- Deck 8: Πρακτικές Ασκήσεις (live coding on Kaggle with OULAD) ----
'8.1':('CUT','','Title slide with two third-party cartoons.'),
'8.2':('CUT','','93 words introducing the OULAD practical. Replaced by Lab 1 on the designed case (approved decision).'),
'8.3':('CUT','','Step 1, create a Kaggle account: the step where a live session loses people.'),
'8.4':('CUT','','Step 2, find the dataset on Kaggle.'),
'8.5':('CUT','','Step 3, new notebook, delete cell.'),
'8.6':('CUT','','Step 4, import the notebook, demo over Zoom. The whole deck is replaced by the Lab 1 student pack and teacher key; the optional Colab notebook gets one line in the pack, not slides.'),
# ---- Deck 9: Βοηθητικό Υλικό (ten full-slide third-party posters, no text, no notes) ----
'9.1':('CUT','','Google Cloud sketchnote (analytics pipeline). Vendor infrastructure; the pipeline idea is already covered by the technology-stack slide of Week 1, Part 2.'),
'9.2':('CUT','','Google Cloud sketchnote (Dataflow).'),
'9.3':('CUT','','Google Cloud sketchnote (BigQuery).'),
'9.4':('CUT','','R cheat sheet. No R anywhere in the new course.'),
'9.5':('CUT','','SQL cheat sheet: belongs to the database half.'),
'9.6':('MERGE','W2·P1 (idea only)','Machine-learning overview poster (supervised / unsupervised, classification, clustering). The idea folds into the single "ερώτημα → οικογένεια μεθόδων" slide together with your 2.6.'),
'9.7':('CUT','','"Top prediction algorithms" poster. The programme has dedicated ML courses.'),
'9.8':('MERGE','W2·P1 (idea only)','Azure "What do you want to do?" cheat sheet (© Microsoft). Its question-first logic is exactly the organising idea of Part 1, so it is rebuilt natively with Learning Analytics questions instead of Azure modules.'),
'9.9':('CUT','','Spark MLlib cheat sheet.'),
'9.10':('MERGE','W2·P3','Chart chooser (comparison, relationship, distribution, composition). Same idea as your 3.26, already routed to the dashboards part: one native slide "ερώτημα → τύπος γραφήματος". Credit line to be verified at the Part 3 outline.'),
}
