# Week 3, Part 3 = frontiers (15') + assignment workshop 2 (30') (outline v1, awaiting approval). One entry per slide: (minutes, flag, Greek title, what is on it, source)
# flag: '' | 'SKIP' | 'TIMER' | 'YOURS' (your own slide or figure, rebuilt or reused)
TITLE = 'Νέες κατευθύνσεις. Εργασία: εξαγωγή δεδομένων και σύνθεση'
OUTLINE = [
('Νέες κατευθύνσεις: τεχνολογίες εμβύθισης', [
 (1,'','Δύο σύνορα του πεδίου','Immersive technologies bring new traces; generative AI brings a new analyst and a new kind of learner behaviour. What does not change: the four questions of Week 1 (Τι; Ποιος; Γιατί; Πώς;).',''),
 (1,'YOURS','Εικονική και επαυξημένη πραγματικότητα: ποια νέα ίχνη παράγουν','Your slide 6.4 turned towards the point of the part: three levels of immersion, three kinds of augmentation, and the traces each device leaves. One-line link to the bio-physiological traces of Week 1, Part 2.','Your deck 6, slide 4'),
 (1,'YOURS','Το κενό: η αναλυτική είναι δεμένη με τα δεδομένα που συλλέγονται εύκολα','Your argument of 6.5, left column: LMS data are reached with minimal effort, so institutional variables dominate and few frameworks exist for immersive settings.','Christopoulos, Pellas & Laakso (2020), Education Sciences 10(11), 317'),
 (1,'YOURS','Το πλαίσιο σε τέσσερις διαστάσεις','6.6 rebuilt natively: Τεχνολογία, Παιδαγωγική, Ψυχολογία, and Μαθησιακή Αναλυτική as the fourth. Your slide says «δεδομένα από 3 διαστάσεις» and the paper says «four-dimensional»: both are right, and the slide says why (three feed the fourth).','Same paper (abstract opened)'),
 (2,'YOURS','Συλλογή δεδομένων: τι, από πού, σε ποια μορφή','Your strongest slide (6.8) as a native table: Τεχνολογικά / Παιδαγωγικά / Ψυχολογικά × πηγή × τύπος × παραδείγματα, in your wording.','Same paper; table read in the full text at build'),
 (1,'SKIP','Από τα δεδομένα στα τέσσερα επίπεδα ανάλυσης','6.7 and 6.9 together: your four guiding questions (Τι έγινε; Γιατί έγινε; Τι θα γίνει; Πώς βελτιώνουμε;) are the «Τύποι αναλυτικής» of Week 1. The model column is shown as «ενδεικτικά, όπως δημοσιεύθηκε»: a CS cohort would otherwise challenge it.','Same paper'),
 (1,'YOURS','Η αρχιτεκτονική του συστήματος','Your figure 6.10 as it is, large (2937 px): the sharpest image of all your decks. The «To be or not to be» graphic is dropped.','Same paper'),
 (1,'YOURS','Το πλαίσιο στην πράξη: εργαστήριο ρομποτικής σε εικονική πραγματικότητα','Your simulator screenshot (7.12), full width. One sentence of context: the VR robotics laboratory of the JANUS project, connected to ViLLE.','See the question on the publication'),
 (1,'YOURS','Τι συλλέχθηκε, πού και πότε','7.13, first half, as a native table: πριν, κατά, μετά την παρέμβαση × κατηγορία × μέσο (LMS survey, LMS quiz, VR assessment). It is the data-collection table of the framework filled in. The statistical tests move to the notes.','Your deck 7, slide 13'),
 (2,'YOURS','Τρία ευρήματα','7.14 condensed: theory improved from pre-test to post-test; almost one in two was correct at the first attempt on all practical aspects; no association between theoretical and practical knowledge, and realism went with perceived difficulty. Why it matters for LA: the VR trace measured something the quiz did not.','See the question on the publication'),
]),
('Νέες κατευθύνσεις: παραγωγική τεχνητή νοημοσύνη', [
 (2,'','Η παραγωγική ΤΝ στον κύκλο της μαθησιακής αναλυτικής','The cycle the students know (εκπαιδευόμενοι, δεδομένα, ανάλυση, παρέμβαση) with what GenAI changes at each step: new learner behaviour, unstructured data made usable, the model as analyst and explainer, dialogic feedback.','Yan, Martinez-Maldonado & Gašević (2024), LAK \'24, 101-111 (abstract opened; full text at build)'),
 (1,'','Τι αλλάζει για όσα μάθατε','Validity: whose trace is it when the student writes with an assistant? (Week 2). Dashboards that explain themselves (Week 2, Part 3). Intervention and oversight (tonight). And the AI rule of your assignment stays exactly as announced in Week 1.','Yan, Greiff, Teuber & Gašević (2024), Nature Human Behaviour 8(10) · Yan et al. (2025), Computers & Education — citations verified, abstracts at build'),
]),
('Εργασία: ενημέρωση', [
 (1,'YOURS','Τι καταγράφουμε','From your revision deck: βιβλιογραφικά, μεθοδολογικά, ευρήματα, mapped onto the columns of sheet 3_Εξαγωγή that they already have. The rule already in the workbook: test the table on three studies before you go on.','Your «Συστηματικές Ανασκοπήσεις: Επανάληψη», slide 10'),
 (1,'','Από τη μελέτη στη γραμμή','One study they met in Part 1 (Hellings & Haelermans, 2022) as one filled row. What belongs in «Κύρια ευρήματα»: the result with its direction, not «η μελέτη εξέτασε…». Replaces the invented «Smith et al.» rows of your deck.','Hellings & Haelermans (2022), opened in Part 1'),
 (1,'YOURS','Σύνθεση: από τις γραμμές στις απαντήσεις','Your rule «κάθε ερευνητικό ερώτημα = μία ενότητα στα Αποτελέσματα» and a NEW sheet, 5_Σύνθεση (workbook v3): one row per claim: ερώτημα, ισχυρισμός, μελέτες υπέρ, μελέτες κατά, βάρος ποιότητας, πρόταση. Results without interpretation; interpretation belongs to the Discussion.','Your revision deck, slide 11 · Campbell et al. (2020), BMJ 368:l6890 (SWiM) — to be opened at build'),
 (1,'YOURS','PRISMA 2020: έλεγχοι στους αριθμούς σας','Sheet PRISMA_αριθμοί fills itself from 2_Επιλογή. Three checks, shown on the example of your own deck, whose numbers do add up (174 − 42 = 132 · 132 − 78 = 54 · 54 − 13 = 41), relabelled to the boxes of PRISMA 2020.','Your revision deck, slide 9 · Page et al. (2021), already on Week 1'),
 (1,'','Πώς δουλεύουμε','One team of about four per Zoom room, one product per room. Handout with three study cards (three studies from Part 1, summarised in my words) and workbook v3. Same set-up as Workshop 1.',''),
]),
('Εργασία: ομάδες και αναφορές', [
 (12,'TIMER','Εργασία στις αίθουσες','Timer 12:00. (Α) three rows of 3_Εξαγωγή from the three cards. (Β) two rows of 5_Σύνθεση for the question «Μειώνουν την εγκατάλειψη οι παρεμβάσεις που στηρίζονται σε πρόβλεψη;». Broadcast at minute 4 and minute 9.',''),
 (5,'TIMER','Δύο ομάδες παρουσιάζουν','Timer 02:30 per team. Fixed format: one extraction row read aloud, then the synthesis sentence. It does not depend on what they wrote.',''),
]),
('Εργασία: τι είδαμε, και ως την υποβολή', [
 (1,'','Οι τρεις μελέτες σε μία πρόταση','The model rows and the model sentence: e-mails did not reduce dropout, goal-setting on the current activity did, a dashboard changed behaviour but not grades. A synthesis is the pattern across studies, not a list of them.','Borrella et al. (2022) · Bañeres et al. (2023) · Hellings & Haelermans (2022), all opened in Part 1'),
 (1,'SKIP','Τέσσερα λάθη στην εξαγωγή και τη σύνθεση','Only what Week 1 did not already say: columns that change from study to study; «ευρήματα» copied from the abstract; claims that rest on one study; counting studies instead of weighing them.','Your revision deck, slide 16, minus the six mistakes of Week 1'),
 (1,'YOURS','Έλεγχος πριν από την υποβολή','Your quality checklist, brought in line with the brief of Week 1 (APA 7, PRISMA, the AI rule, the rubric) and with one new block: Discussion and limitations.','Your revision deck, slides 13 and 17'),
 (1,'','Έως την υποβολή','What is left, in order: full texts, stage 2, extraction, quality, synthesis, writing. The deadline is on the course platform (no date on the slide).',''),
]),
('Κλείσιμο', [
 (1,'','Να θυμάστε: τρία σημεία από το Μέρος 3','Νέα ίχνη και νέα εργαλεία, ίδια τέσσερα ερωτήματα. · Η εξαγωγή γίνεται με ίδιες στήλες για όλες τις μελέτες· η σύνθεση απαντά σε ερωτήματα, δεν παραθέτει περιλήψεις. · Οι αριθμοί του PRISMA αθροίζονται, και κάθε αποκλεισμός έχει λόγο.',''),
 (3,'','Ερωτήσεις','End slide of the evening and of the Learning Analytics block. Carries the 3 minutes of slack.',''),
]),
]
# Audit of the sources for this part
AUDIT = [
 ('Deck 6, slides 1 and 3', 'CUT', 'Title on a third-party cartoon; a recap of what Learning Analytics is, on stock clip-art. Both decided in the Week 2 audit.', 'Nothing.'),
 ('Deck 6, slides 2, 4, 5, 6, 7, 8, 9', 'REBUILD', 'Your framework: good content in overlapping text boxes and pictures of diagrams. One discrepancy checked: the slide says three dimensions of data, the paper says a four-dimensional framework.', 'Slides 2 to 6 of this part, natively, in your wording. Slide 6 (analysis levels) is skippable.'),
 ('Deck 6, slide 10: system architecture', 'KEEP', '2937 × 1150 px, your own composition. Already extracted into the kit.', 'Slide 7, as it is.'),
 ('Deck 7, slides 12-14: VR robotics study', 'KEEP', 'Sharp simulator screenshot (1920 px); 124 and 91 words in English on 13 and 14. No publication on the slides.', 'Slides 8 to 10. The publication is the one question below.'),
 ('Deck 7, slides 15-16', 'CUT', '15 is a collage of ViLLE charts, considered for the dashboards part of Week 2 and not used; 16 is empty.', 'Nothing.'),
 ('SR revision deck, slides 1-8, 14, 15, 18-20', 'CUT', 'Types of review, PICO/PCC, databases, Boolean, criteria, selection, structure, APA: all taught in Week 1, Part 3 and Workshop 1. Slide 4 teaches the four phases of PRISMA 2009, while Week 1 teaches PRISMA 2020.', 'Not repeated. The APA examples and the list of resources go to the handout after each link and format is checked.'),
 ('SR revision deck, slides 9, 10, 11, 13, 16, 17', 'KEEP', 'Exactly the material of workshop 2. To fix: the extraction example uses invented studies; «Cohen\'s κ ≥ 0,80» and «Abstract 150-250 λέξεις» are not in the brief of Week 1.', 'Slides 13, 15, 16, 21 and 22. The invented studies are replaced by real ones from Part 1; the two items that are not in the brief are left out unless you tell me they belong to it.'),
 ('SR revision deck, slide 12: presenting results', 'MERGE', 'Week 1, Part 3 (slide 23) already lists what the Results must show.', 'One line on slide 15.'),
]
DELIVER = ['W3P3.html and the student PDF', 'Workshop2_handout.pdf: instructions, three study cards, the synthesis question, APA 7 mini-reference', 'Workshop2_teacher.pdf: run sheet, the two messages, model rows, model synthesis, the errors you will see', 'LA_review_templates_v3.xlsx: the workbook with the new sheet 5_Σύνθεση (who already works in v2 copies only that sheet)', 'The two-page revision sheet from the nine «Να θυμάστε» slides of the three weeks', 'LA_Week3_package.zip, complete, and the updated kit']
SOURCES = [
 ('Christopoulos, Pellas & Laakso (2020). A Learning Analytics Theoretical Framework for STEM Education Virtual Reality Applications. Education Sciences 10(11), 317. doi:10.3390/educsci10110317', 'Abstract and front page on the University of Turku repository: four-dimensional framework, prototype system, LMS data as the easy data. This is the paper behind deck 6. Tables and figure are read in the open-access full text at build.', 'OPENED'),
 ('Antonelli, Christopoulos, Laakso, Dagienė, Juškevičienė, Masiulionytė-Dagienė, Mądziel, Stadnicka & Stylios (2023). A Virtual Reality Laboratory for Blended Learning Education. Education Sciences 13(5), 528. doi:10.3390/educsci13050528', 'Abstract: JANUS project, VR robotics laboratory integrated with ViLLE, two VR workshops, favourable responses, performance measured indirectly. It is my best candidate for slides 7.12-7.14, but I cannot confirm from the abstract that the findings of 7.14 are reported there.', 'ASK'),
 ('Yan, Martinez-Maldonado & Gašević (2024). Generative artificial intelligence in learning analytics. LAK \'24, 101-111. doi:10.1145/3636555.3636856', 'Citation on four independent lists and the opening of the abstract. Full text at build.', 'OPENED'),
 ('Yan, Greiff, Teuber & Gašević (2024), Nature Human Behaviour 8(10), 1839-1850 · Yan et al. (2025), Computers & Education · the Journal of Learning Analytics special section on GenAI', 'Citations seen; nothing read. Each goes on a slide only after its abstract is opened.', 'TODO'),
 ('Campbell et al. (2020), Synthesis without meta-analysis (SWiM), BMJ 368:l6890 · Page et al. (2021), PRISMA 2020', 'PRISMA 2020 was verified in Week 1. SWiM is my own knowledge and is opened at build; if it does not fit, the synthesis slide stands on your own rule.', 'TODO'),
 ('The three study cards of the handout', 'Borrella et al. (2022), Bañeres et al. (2023), Hellings & Haelermans (2022): all opened for Part 1. The cards are written in my own words from their abstracts; the students get the DOIs.', 'OPENED'),
]
