use library
db.books.findOne()
db.books.findOne({}, { title: 1, pageCount: 1, status: 1, authors: 1, categories: 1, publishedDate: 1 })
db.books.find({ categories: "Internet", pageCount: { $gte: 400, $lte: 500 } }, { longDescription: 0 }).count
db.books.countDocuments({ categories: "Internet", pageCount: { $gte: 400, $lte: 500 } })
db.books.find({}, { title: 1, longDescription: 0 })
db.books.countDocuments({ categories: "Java" })
db.books.countDocuments({ categories: ["Java"] })
db.books.countDocuments({ categories: "java" })
db.books.countDocuments({ pageCount: 0 })
db.books.countDocuments({ categories: { $size: 0 } })
db.books.countDocuments({ authors: "" })
db.books.countDocuments({ status: "MEAP" })
db.books.countDocuments({ pageCount: { $gt: 300 }, pageCount: { $lt: 400 } })
db.books.countDocuments({ pageCount: { $gt: 300, $lt: 400 } })
db.books.countDocuments({ pageCount: { $lt: 400 } })
db.books.countDocuments({ authors: { $elemMatch: { $regex: "^Peter", $options: "i" } } })
db.books.countDocuments({ authors: { $regex: "^Peter", $options: "i" } })
db.books.countDocuments({ authors: /^Peter/ })
db.books.countDocuments({ authors: { $elemMatch: { $regex: "Piter" } } })
db.books.countDocuments({ title: /Java/ })
db.books.countDocuments({ title: /^Java/ })
db.books.countDocuments({ title: /^.a.a/ })
db.books.countDocuments({ title: { $regex: "java", $options: "i" } })
db.books.countDocuments({ "authors.0": "Peter Armstrong" })
db.books.countDocuments({ categories: { $all: ["Java", "Internet"] } })
db.books.countDocuments({ categories: { $in: ["Python", "Perl"] } })
db.books.countDocuments({ $or: [ { categories: "Python" }, { pageCount: { $gt: 1000 } } ] })
db.books.countDocuments({ pageCount: { $gt: 1000 } })
db.books.find({ pageCount: { $gt: 1000 } }, { title: 1, pageCount: 1, _id: 0 })
db.books.find({}, { title: 1, pageCount: 1, _id: 0 }).sort({ pageCount: -1 }).limit(5)
db.books.find({}, { title: 1, _id: 0 }).sort({ title: 1 }).skip(10).limit(5)
db.books.count()
db.books.find({ categories: "Python" }, { title: 1, _id: 0 }).forEach(printjson)
