# NoSQL Evening 2, Part 1: every mongosh statement shown on a slide or quoted in a note.
# One key per pane; each value is a list of statements, written exactly as displayed.
# run_e2p1.py executes them (whitespace collapsed to one line) and stores the real outputs in e2p1_outputs.json;
# make_n2p1.py builds the slides from the same statements and those outputs, so a slide cannot show a command that was not run.
CMDS = {
    'book23': ['use library', 'db.books.findOne({ _id: 23 })'],
    'counts': ['db.books.countDocuments({ status: "MEAP" })',
               'db.books.countDocuments({ pageCount: 0 })',
               'db.books.countDocuments({ status: "MEAP", pageCount: 0 })',
               'db.books.countDocuments({ categories: "Internet" })',
               'db.books.countDocuments({ categories: "internet" })'],
    'total': ['db.books.countDocuments()'],
    'count_old': ['db.books.count()'],
    'proj1': ['db.books.find(\n  { categories: "Python" },\n  { title: 1, pageCount: 1 }\n)'],
    'proj2': ['db.books.find(\n  { categories: "Python" },\n  { title: 1, pageCount: 1, _id: 0 }\n)'],
    'projerr': ['db.books.find({}, { title: 1, longDescription: 0 })'],
    'printjson': ['db.books.find(\n  { categories: "Open Source" },\n  { title: 1, categories: 1, _id: 0 }\n).forEach(printjson)'],
    'pretty': ['db.books.find({ categories: "Mobile" }, { title: 1, _id: 0 }).pretty()'],
    'vars': ['var python = { categories: "Python" }',
             'var fields = { title: 1, _id: 0 }',
             'db.books.find(python, fields)',
             'db.books.countDocuments(python)'],
    'gt': ['db.books.find(\n  { pageCount: { $gt: 1000 } },\n  { title: 1, pageCount: 1, _id: 0 }\n)'],
    'in': ['db.books.countDocuments({ categories: { $in: ["Python", "Perl"] } })'],
    'not': ['db.books.countDocuments({ pageCount: { $not: { $gt: 500 } } })'],
    'ex1': ['db.books.find(\n  { categories: "Internet",\n    pageCount: { $gte: 400, $lte: 500 } },\n  { longDescription: 0 }\n)',
            'db.books.countDocuments({ categories: "Internet",\n  pageCount: { $gte: 400, $lte: 500 } })'],
    'ex1fix': ['db.books.countDocuments({ categories: { $in: ["Internet", "internet"] },\n  pageCount: { $gte: 400, $lte: 500 } })'],
    'ex1miss': ['db.books.find({ categories: "internet" }, { title: 1, pageCount: 1, categories: 1, _id: 0 })'],
    'or': ['db.books.find(\n  { $or: [ { categories: "Python" },\n           { pageCount: { $gt: 1000 } } ] },\n  { title: 1, _id: 0 }\n)'],
    'samefield': ['db.books.countDocuments({ pageCount: { $gt: 300 },\n                          pageCount: { $lt: 400 } })',
                  'db.books.countDocuments({ pageCount: { $gt: 300, $lt: 400 } })',
                  'db.books.countDocuments({ $and: [ { pageCount: { $gt: 300 } },\n                                  { pageCount: { $lt: 400 } } ] })'],
    'lt400': ['db.books.countDocuments({ pageCount: { $lt: 400 } })'],
    'perl': ['db.books.find(\n  { categories: "Perl" },\n  { title: 1, categories: 1, _id: 0 }\n)'],
    'exact': ['db.books.countDocuments({ categories: "Internet" })',
              'db.books.countDocuments({ categories: ["Internet"] })'],
    'all': ['db.books.countDocuments({ categories: { $all: ["Internet", "XML"] } })'],
    'dot': ['db.books.find(\n  { "authors.0": "Christian Bauer" },\n  { title: 1, _id: 0 }\n)'],
    'dotall': ['db.books.countDocuments({ authors: "Christian Bauer" })'],
    'regex': ['db.books.countDocuments({ title: /Python/ })',
              'db.books.countDocuments({ title: /python/ })',
              'db.books.countDocuments({ title: /python/i })',
              'db.books.countDocuments({ title: { $regex: "Python" } })'],
    'pytitles': ['db.books.find({ title: /Python/, categories: { $ne: "Python" } }, { title: 1, categories: 1, _id: 0 })'],
    'symbols': ['db.books.countDocuments({ title: /^The / })',
                'db.books.countDocuments({ title: /Edition$/ })',
                'db.books.find({ title: /^.#/ }, { title: 1, _id: 0 })'],
    'escape': ['db.books.countDocuments({ title: /\\.NET/ })'],
    'elem': ['db.books.countDocuments({ authors: /^Chris/ })',
             'db.books.countDocuments({ authors: { $elemMatch:\n    { $regex: "^Chris", $ne: "Christian Bauer" } } })'],
    'ex2find': ['db.books.find({ authors: { $elemMatch: { $regex: "^Peter", $options: "i" } } }, { title: 1, authors: 1, _id: 0 })'],
    'ex2': ['db.books.countDocuments({ authors: { $elemMatch:\n    { $regex: "^Peter", $options: "i" } } })',
            'db.books.countDocuments({ authors: /^Peter/ })'],
    'piter': ['db.books.countDocuments({ authors: { $elemMatch: { $regex: "^Piter", $options: "i" } } })'],
    'sort': ['db.books.find({}, { title: 1, publishedDate: 1, _id: 0 })\n  .sort({ publishedDate: -1 })\n  .limit(3)'],
    'skip': ['db.books.find({}, { title: 1, publishedDate: 1, _id: 0 })\n  .sort({ publishedDate: -1 })\n  .skip(3)\n  .limit(3)'],
    'zeros': ['db.books.find({}, { title: 1, pageCount: 1, _id: 0 })\n  .sort({ pageCount: 1 })\n  .limit(3)'],
    'zerosfix': ['db.books.find({ pageCount: { $gt: 0 } }, { title: 1, pageCount: 1, _id: 0 })\n  .sort({ pageCount: 1 })\n  .limit(3)'],
    'idtypes': ['db.books.countDocuments({ _id: { $type: "int" } })',
                'db.books.countDocuments({ _id: { $type: "objectId" } })'],
}
IMPORT = 'mongoimport books.json -d library -c books --drop'
IMPORT_AGAIN = 'mongoimport books.json -d library -c books'
