# NoSQL Evening 2, Part 2 (group exercise): the colleague's optional exercises B36-39, updated, each with its SQL form.
# 'orig' = his wording or solution where the old slides had one; 'task' = the updated wording on the student sheet.
# 'find' = the solution as displayed; 'count' = the same filter with countDocuments; 'show' = what the answers file prints.
SHEET = [
    dict(n=1, task='Το πλήθος των βιβλίων.', sql='SELECT COUNT(*) FROM books',
         find='db.books.countDocuments()', count=None, show='db.books.countDocuments()',
         orig='db.books.count()'),
    dict(n=2, task='Όλα τα βιβλία.', sql='SELECT * FROM books',
         find='db.books.find()', count='db.books.countDocuments()', show=None, orig='db.books.find();'),
    dict(n=3, task='Το _id, το status και τις κατηγορίες όλων των βιβλίων.', sql='SELECT _id, status, category FROM books',
         find='db.books.find({}, { _id: 1, status: 1, categories: 1 })', count='db.books.countDocuments()',
         show='db.books.find({}, { _id: 1, status: 1, categories: 1 }).limit(2)', orig='db.books.find({},{_id:1, status:1, categories:1});'),
    dict(n=4, task='Τα βιβλία της κατηγορίας Java.', sql="SELECT * FROM books WHERE category = 'Java'",
         find='db.books.find({ categories: "Java" })', count='db.books.countDocuments({ categories: "Java" })', show=None,
         orig='db.books.find({categories: “Java});'),
    dict(n=5, task='Τα βιβλία της κατηγορίας Java που έχουν κυκλοφορήσει (status PUBLISH).',
         sql="SELECT * FROM books WHERE category = 'Java' AND status = 'PUBLISH'",
         find='db.books.find({ categories: "Java", status: "PUBLISH" })',
         count='db.books.countDocuments({ categories: "Java", status: "PUBLISH" })', show=None,
         orig='db.books.find({categories: “Java”, status: “PUBLISH”});'),
    dict(n=6, task='Τα βιβλία που είτε ανήκουν στην κατηγορία Java είτε έχουν κυκλοφορήσει.',
         sql="SELECT * FROM books WHERE category = 'Java' OR status = 'PUBLISH'",
         find='db.books.find({ $or: [ { categories: "Java" }, { status: "PUBLISH" } ] })',
         count='db.books.countDocuments({ $or: [ { categories: "Java" }, { status: "PUBLISH" } ] })', show=None, orig=None),
    dict(n=7, task='Οι τίτλοι των βιβλίων με περισσότερες από 500 σελίδες.', sql='SELECT title FROM books WHERE pageCount > 500',
         find='db.books.find({ pageCount: { $gt: 500 } }, { title: 1, _id: 0 })',
         count='db.books.countDocuments({ pageCount: { $gt: 500 } })', show=None, orig=None),
    dict(n=8, task='Το _id και ο τίτλος των βιβλίων Java, σε αλφαβητική σειρά τίτλου.',
         sql="SELECT _id, title FROM books WHERE category = 'Java' ORDER BY title",
         find='db.books.find({ categories: "Java" }, { title: 1 }).sort({ title: 1 })',
         count='db.books.countDocuments({ categories: "Java" })',
         show='db.books.find({ categories: "Java" }, { title: 1 }).sort({ title: 1 }).limit(3)', orig=None),
    dict(n=9, task='Ο αριθμός σελίδων και ο τίτλος των βιβλίων Java, κατά φθίνουσα σειρά σελίδων.',
         sql="SELECT pageCount, title FROM books WHERE category = 'Java' ORDER BY pageCount DESC",
         find='db.books.find({ categories: "Java" }, { pageCount: 1, title: 1, _id: 0 }).sort({ pageCount: -1 })',
         count='db.books.countDocuments({ categories: "Java" })',
         show='db.books.find({ categories: "Java" }, { pageCount: 1, title: 1, _id: 0 }).sort({ pageCount: -1 }).limit(3)', orig=None),
    dict(n=10, task='Ο αριθμός σελίδων και ο τίτλος των πέντε βιβλίων με τις περισσότερες σελίδες.',
         sql='SELECT pageCount, title FROM books ORDER BY pageCount DESC LIMIT 5',
         find='db.books.find({}, { pageCount: 1, title: 1, _id: 0 }).sort({ pageCount: -1 }).limit(5)', count=None,
         show='db.books.find({}, { pageCount: 1, title: 1, _id: 0 }).sort({ pageCount: -1 }).limit(5)', orig=None),
    dict(n=11, task='Οι τίτλοι που περιέχουν τη λέξη Java.', sql="SELECT title FROM books WHERE title LIKE '%Java%'",
         find='db.books.find({ title: /Java/ }, { title: 1, _id: 0 })', count='db.books.countDocuments({ title: /Java/ })', show=None, orig=None),
    dict(n=12, task='Οι τίτλοι που αρχίζουν από τη λέξη Java.', sql="SELECT title FROM books WHERE title LIKE 'Java%'",
         find='db.books.find({ title: /^Java/ }, { title: 1, _id: 0 })', count='db.books.countDocuments({ title: /^Java/ })', show=None, orig=None),
    dict(n=13, task='Οι τίτλοι με δεύτερο και τέταρτο χαρακτήρα το a.', sql="SELECT title FROM books WHERE title LIKE '_a_a%'",
         find='db.books.find({ title: /^.a.a/ }, { title: 1, _id: 0 })', count='db.books.countDocuments({ title: /^.a.a/ })',
         show='db.books.find({ title: /^.a.a/ }, { title: 1, _id: 0 }).limit(3)', orig=None),
]
# panes of the deck (as displayed; the runner collapses whitespace to execute them)
CMDS = {
    'example': ['db.books.find(\n  { status: "MEAP", pageCount: { $gt: 0 } },\n  { title: 1, pageCount: 1, _id: 0 }\n).sort({ pageCount: -1 }).limit(3)'],
    'java': ['db.books.countDocuments({ categories: "Java" })',
             'db.books.countDocuments({ categories: ["Java"] })',
             'db.books.countDocuments({ categories: "java" })',
             'db.books.countDocuments({ categories: { $in: ["Java", "java"] } })'],
    'andor': ['db.books.countDocuments({ categories: "Java", status: "PUBLISH" })',
              'db.books.countDocuments({ $or: [ { categories: "Java" },\n                                 { status: "PUBLISH" } ] })',
              'db.books.countDocuments({ status: "PUBLISH" })',
              'db.books.countDocuments({ categories: "Java", status: "MEAP" })'],
    'sortcase': ['db.books.find({ categories: "Java" }, { title: 1, _id: 0 })\n  .sort({ title: -1 }).limit(3)',
                 'db.books.find({ categories: "Java" }, { title: 1, _id: 0 })\n  .sort({ title: -1 }).collation({ locale: "en" }).limit(3)'],
    'regex': ['db.books.countDocuments({ title: /Java/ })',
              'db.books.countDocuments({ title: /\\bJava\\b/ })',
              'db.books.countDocuments({ title: /^Java/ })',
              'db.books.countDocuments({ title: /^Java\\b/ })'],
    'javascript': ['db.books.find({ title: /^Java\\B/ }, { title: 1, _id: 0 })'],
    'curly': ['db.books.find({categories: “Java});'],
    'unclosed': ['db.books.find({ categories: "Java })'],
    'count_old': ['db.books.count()'],
    'java_lc': ['db.books.find({ categories: "java" }, { title: 1, categories: 1, _id: 0 })'],
    'zeros_java': ['db.books.countDocuments({ categories: "Java", pageCount: 0 })'],
}

# N2P2 slide 6 and the sheet: every team posts the counts of all items in the chat; items from PRESENT_FROM on are presented,
# items 1-3 (plain count, all books, a projection) are checked through the chat counts only (README v16.1)
PRESENT_FROM = 4
