# NoSQL Evening 2, Part 3: every statement shown on a slide, in slide order (the updates depend on it). run_e2p3.py executes them.
# Starting state = the end of Evening 1: world.country holds Greece, France and Germany; library.books freshly imported; persons loaded from persons.txt.
PANES = [
    ('upd_set', ['use world', 'db.country.updateOne(\n  { name: "Greece" },\n  { $set: { capital: { name: "Athens", timezone: "Europe/Athens" } } }\n)']),
    ('upd_again', ['db.country.updateOne(\n  { name: "Greece" },\n  { $set: { capital: { name: "Athens", timezone: "Europe/Athens" } } }\n)']),
    ('upd_incpush', ['db.country.updateOne(\n  { name: "Greece" },\n  { $inc: { visits: 1 }, $push: { languages: "Greek" } }\n)', 'db.country.findOne({ name: "Greece" }, { _id: 0 })']),
    ('upd_unset', ['db.country.updateOne({ name: "Greece" }, { $unset: { visits: "" } })']),
    ('upd_one_first', ['db.country.updateOne({ euSince: 1958 }, { $set: { founder: true } })', 'db.country.countDocuments({ founder: true })']),
    ('upd_many_founder', ['db.country.updateMany({ euSince: 1958 }, { $set: { founder: true } })']),
    ('upd_many_books', ['use library', 'db.books.updateMany({ pageCount: 0 }, { $unset: { pageCount: "" } })', 'db.books.countDocuments({ pageCount: { $exists: false } })']),
    ('upsert', ['use world', 'db.country.updateOne(\n  { name: "Cyprus" },\n  { $set: { population: 980000 } },\n  { upsert: true }\n)', 'db.country.findOne({ name: "Cyprus" }, { _id: 0 })']),
    ('poll', ['db.country.updateOne({ name: "Greece" },\n                     { population: 10500000 })']),
    ('count_first', ['db.country.countDocuments({ population: { $lt: 1000000 } })']),
    ('delmany', ['db.country.deleteMany({ population: { $lt: 1000000 } })']),
    ('agg_total', ['db.country.aggregate([\n  { $group: { _id: null, totalPopulation: { $sum: "$population" } } }\n])']),
    ('agg_status', ['use library', 'db.books.aggregate([\n  { $group: { _id: "$status", books: { $sum: 1 } } }\n])']),
    ('agg_java', ['db.books.aggregate([\n  { $match: { categories: "Java" } },\n  { $group: { _id: "$status", books: { $sum: 1 },\n              avgPages: { $avg: "$pageCount" },\n              maxPages: { $max: "$pageCount" } } }\n])']),
    ('agg_unwind', ['db.books.aggregate([\n  { $unwind: "$categories" },\n  { $group: { _id: "$categories", books: { $sum: 1 } } },\n  { $sort: { books: -1 } },\n  { $limit: 5 }\n])']),
    ('agg_having', ['db.books.aggregate([\n  { $unwind: "$categories" },\n  { $group: { _id: "$categories", books: { $sum: 1 } } },\n  { $match: { books: { $gte: 12 } } },\n  { $sort: { books: -1, _id: 1 } }\n])']),
    ('agg_project', ['db.books.aggregate([\n  { $match: { categories: "Java" } },\n  { $group: { _id: "$status", books: { $sum: 1 },\n              avgPages: { $avg: "$pageCount" } } },\n  { $project: { _id: 0, status: "$_id", books: 1,\n                avgPages: { $round: ["$avgPages", 0] } } }\n])']),
    ('persons_pipeline', ['db = db.getSiblingDB("book-filtered-top-subset")', 'var pipeline = [\n  { $match: { vocation: "ENGINEER" } },\n  { $sort: { dateofbirth: -1 } },\n  { $limit: 3 },\n  { $unset: ["_id", "vocation", "address"] }\n]', 'db.persons.aggregate(pipeline)']),
    ('persons_project', ['db.persons.aggregate([\n  { $match: { vocation: "ENGINEER" } },\n  { $sort: { dateofbirth: -1 } },\n  { $limit: 3 },\n  { $project: { _id: 0, vocation: 0, address: 0 } }\n])']),
    ('persons_find', ['db.persons.find(\n  { vocation: "ENGINEER" },\n  { _id: 0, vocation: 0, address: 0 }\n).sort({ dateofbirth: -1 }).limit(3)']),
    ('persons_group', ['db.persons.aggregate([\n  { $group: { _id: "$vocation", people: { $sum: 1 },\n              oldest: { $min: "$dateofbirth" } } },\n  { $sort: { people: -1, _id: 1 } }\n])']),
]
